//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum CurrentStatus : int
    {
        NotStarted = 0,
        Running = 1,
        OnHold = 2,
        Released = 3,
        RecoverableError = 4,
        UnrecoverableError = 5
    }
}
