//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edition
    {
        public int Id { get; set; }
        public System.DateTime RunningStarted { get; set; }
        public int MaxMissingPages { get; set; }
        public bool Running { get; set; }
        public string Log { get; set; }
        public string ErrorMessage { get; set; }
        public int PublicationId { get; set; }
    
        public virtual Publication Publication { get; set; }
    }
}
