//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelClassesContainer : DbContext
    {
        public ModelClassesContainer()
            : base("name=ModelClassesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Publication> PublicationSet { get; set; }
        public virtual DbSet<Edition> EditionSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
    }
}
