//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.langResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVR-nr.
        /// </summary>
        internal static string Views_Home_Contact_cvr {
            get {
                return ResourceManager.GetString("Views_Home_Contact_cvr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Views_Home_Contact_email {
            get {
                return ResourceManager.GetString("Views_Home_Contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Views_Home_Contact_support {
            get {
                return ResourceManager.GetString("Views_Home_Contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Views_Home_Contact_telephone {
            get {
                return ResourceManager.GetString("Views_Home_Contact_telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Views_Home_Contact_Title {
            get {
                return ResourceManager.GetString("Views_Home_Contact_Title", resourceCulture);
                }
                }
               /// <summary>
        ///   Looks up a localized string similar to Nuværende status:.
        /// </summary>
        internal static string Views_Home_Details_currentStatus {
            get {
                return ResourceManager.GetString("Views_Home_Details_currentStatus", resourceCulture);
            }
        }

/// <summary>
        ///   Looks up a localized string similar to Udgave ID:.
        /// </summary>
        internal static string Views_Home_Details_editionID {
            get {
                return ResourceManager.GetString("Views_Home_Details_editionID", resourceCulture);
            }
        }
/// <summary>
        ///   Looks up a localized string similar to Forventet udgivelsestid:.
        /// </summary>
        internal static string Views_Home_Details_expectedReleaseTime {
            get {
                return ResourceManager.GetString("Views_Home_Details_expectedReleaseTime", resourceCulture);
            }
        }
/// <summary>
        ///   Looks up a localized string similar to Skjul log.
        /// </summary>
        internal static string Views_Home_Details_hideLog {
            get {
                return ResourceManager.GetString("Views_Home_Details_hideLog", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Sidste logtjek:.
        /// </summary>
        internal static string Views_Home_Details_lastLogCheck {
            get {
                return ResourceManager.GetString("Views_Home_Details_lastLogCheck", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Logtekst:.
        /// </summary>
        internal static string Views_Home_Details_logText {
            get {
                return ResourceManager.GetString("Views_Home_Details_logText", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Antal sider:.
        /// </summary>
        internal static string Views_Home_Details_numberOfPages {
            get {
                return ResourceManager.GetString("Views_Home_Details_numberOfPages", resourceCulture);
            }
        }
        internal static string Views_Home_Details_pageTolerance {
            get {
                return ResourceManager.GetString("Views_Home_Details_pageTolerance", resourceCulture);
            }
        }
        /// <summary>

        ///   Looks up a localized string similar to PublikationsID:.
        /// </summary>
        internal static string Views_Home_Details_publicationID {
            get {
                return ResourceManager.GetString("Views_Home_Details_publicationID", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Publikationsnavn:.
        /// </summary>
        internal static string Views_Home_Details_publicationName {
            get {
                return ResourceManager.GetString("Views_Home_Details_publicationName", resourceCulture);
            }
        }
/// <summary>
        ///   Looks up a localized string similar to Udgiv.
        /// </summary>
        internal static string Views_Home_Details_release {
            get {
                return ResourceManager.GetString("Views_Home_Details_release", resourceCulture);
            }
        }

/// <summary>
        ///   Looks up a localized string similar to Kør igen.
        /// </summary>
        internal static string Views_Home_Details_rerun {
            get {
                return ResourceManager.GetString("Views_Home_Details_rerun", resourceCulture);
            }
        }
/// <summary>
        ///   Looks up a localized string similar to Start af kørsel:.
        /// </summary>
        internal static string Views_Home_Details_runningStarted {
            get {
                return ResourceManager.GetString("Views_Home_Details_runningStarted", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Vis log.
        /// </summary>
        internal static string Views_Home_Details_showLog {
            get {
                return ResourceManager.GetString("Views_Home_Details_showLog", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Ukendt.
        /// </summary>
        internal static string Views_Home_Details_unknown {
            get {
                return ResourceManager.GetString("Views_Home_Details_unknown", resourceCulture);
            }
        }
        
/// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Views_Home_Details_Title {
            get {
                return ResourceManager.GetString("Views_Home_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username required.
        ///   Looks up a localized string similar to Brugernavn skal indtastes.
        /// </summary>
        internal static string Views_Home_Index_errMsg1 {
            get {
                return ResourceManager.GetString("Views_Home_Index_errMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string Views_Home_Index_errMsg2 {
            get {
                return ResourceManager.GetString("Views_Home_Index_errMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred. The system will try to run the files again in 10 minutes..
        /// </summary>
        internal static string Views_Home_Index_errMsg3 {
            get {
                return ResourceManager.GetString("Views_Home_Index_errMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing page from section.
        /// </summary>
        internal static string Views_Home_Index_errMsg4 {
            get {
                return ResourceManager.GetString("Views_Home_Index_errMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing page: Section {0} page {1}.
        /// </summary>
        internal static string Views_Home_Index_MissingPages {
            get {
                return ResourceManager.GetString("Views_Home_Index_MissingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Views_Home_Index_ok {
            get {
                return ResourceManager.GetString("Views_Home_Index_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Views_Home_Index_online {
            get {
                return ResourceManager.GetString("Views_Home_Index_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string Views_Home_Index_page {
            get {
                return ResourceManager.GetString("Views_Home_Index_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pages.
        /// </summary>
        internal static string Views_Home_Index_pages {
            get {
                return ResourceManager.GetString("Views_Home_Index_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Views_Home_Index_SearchButton {
            get {
                return ResourceManager.GetString("Views_Home_Index_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Views_Home_Index_SearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("Views_Home_Index_SearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded and ready for realease.
        /// </summary>
        internal static string Views_Home_Index_sysMsg1 {
            get {
                return ResourceManager.GetString("Views_Home_Index_sysMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        internal static string Views_Home_Index_Title {
            get {
                return ResourceManager.GetString("Views_Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Views_Home_Login_login {
            get {
                return ResourceManager.GetString("Views_Home_Login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Views_Home_Login_password {
            get {
                return ResourceManager.GetString("Views_Home_Login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Views_Home_Login_username {
            get {
                return ResourceManager.GetString("Views_Home_Login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Views_Shared__Layout_contact {
            get {
                return ResourceManager.GetString("Views_Shared__Layout_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Views_Shared__Layout_users {
            get {
                return ResourceManager.GetString("Views_Shared__Layout_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Views_Shared__LoginPartial_login {
            get {
                return ResourceManager.GetString("Views_Shared__LoginPartial_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Views_Shared__LoginPartial_logoff {
            get {
                return ResourceManager.GetString("Views_Shared__LoginPartial_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Views_Users_Create_ChooseLanguage {
            get {
                return ResourceManager.GetString("Views_Users_Create_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Views_Users_Create_create {
            get {
                return ResourceManager.GetString("Views_Users_Create_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string Views_Users_Create_createNew {
            get {
                return ResourceManager.GetString("Views_Users_Create_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you will delete this user?.
        /// </summary>
        internal static string Views_Users_Delete_areYouSure {
            get {
                return ResourceManager.GetString("Views_Users_Delete_areYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Views_Users_Delete_cancel {
            get {
                return ResourceManager.GetString("Views_Users_Delete_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Views_Users_Delete_delete {
            get {
                return ResourceManager.GetString("Views_Users_Delete_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user {0} ({1})?.
        /// </summary>
        internal static string Views_Users_Delete_MainQuestion {
            get {
                return ResourceManager.GetString("Views_Users_Delete_MainQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string Views_Users_Delete_Title {
            get {
                return ResourceManager.GetString("Views_Users_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string Views_Users_Edit_back {
            get {
                return ResourceManager.GetString("Views_Users_Edit_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string Views_Users_Edit_editUser {
            get {
                return ResourceManager.GetString("Views_Users_Edit_editUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Views_Users_Edit_language {
            get {
                return ResourceManager.GetString("Views_Users_Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Views_Users_Edit_name {
            get {
                return ResourceManager.GetString("Views_Users_Edit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Views_Users_Edit_password {
            get {
                return ResourceManager.GetString("Views_Users_Edit_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Views_Users_Edit_save {
            get {
                return ResourceManager.GetString("Views_Users_Edit_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administrator.
        /// </summary>
        internal static string Views_Users_Edit_userAdministrator {
            get {
                return ResourceManager.GetString("Views_Users_Edit_userAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Views_Users_Edit_username {
            get {
                return ResourceManager.GetString("Views_Users_Edit_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        internal static string Views_Users_Edit_workplace {
            get {
                return ResourceManager.GetString("Views_Users_Edit_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write access to publications.
        /// </summary>
        internal static string Views_Users_Edit_writeAccess {
            get {
                return ResourceManager.GetString("Views_Users_Edit_writeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Views_Users_Index_administrator {
            get {
                return ResourceManager.GetString("Views_Users_Index_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Views_Users_Index_create {
            get {
                return ResourceManager.GetString("Views_Users_Index_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new User.
        /// </summary>
        internal static string Views_Users_Index_createNewUser {
            get {
                return ResourceManager.GetString("Views_Users_Index_createNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Views_Users_Index_delete {
            get {
                return ResourceManager.GetString("Views_Users_Index_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Views_Users_Index_edit {
            get {
                return ResourceManager.GetString("Views_Users_Index_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Views_Users_Index_name {
            get {
                return ResourceManager.GetString("Views_Users_Index_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Views_Users_Index_username {
            get {
                return ResourceManager.GetString("Views_Users_Index_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Views_Users_Index_users {
            get {
                return ResourceManager.GetString("Views_Users_Index_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        internal static string Views_Users_Index_workplace {
            get {
                return ResourceManager.GetString("Views_Users_Index_workplace", resourceCulture);
            }
        }
    }
}
